instrument_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('instruments/', views.instruments_index, name='index'),
    path('instruments/<int:instrument_id>/', views.instruments_detail, name='detail'),
    path('instruments/create/', views.InstrumentCreate.as_view(), name='instruments_create'),
    path('instruments/<int:pk>/update/', views.InstrumentUpdate.as_view(), name='instruments_update'),
    path('instruments/<int:pk>/delete/', views.InstrumentDelete.as_view(), name='instruments_delete'),
    path('instruments/<int:instrument_id>/add_practice/', views.add_practice, name='add_practice'),
    path('instruments/<int:instrument_id>/add_photo/', views.add_photo, name='add_photo'),
    path('instruments/<int:instrument_id>/assoc_product/<int:product_id>/', views.assoc_product, name='assoc_product'),
    path('instruments/<int:instrument_id>/dissoc_product/<int:product_id>/', views.dissoc_product, name='dissoc_product'),
    path('products/', views.ProductList.as_view(), name='products_index'),
    path('products/<int:pk>/', views.ProductDetail.as_view(), name='products_detail'),
    path('products/<int:pk>/update/', views.ProductUpdate.as_view(), name='products_update'),
    path('products/<int:pk>/delete/', views.ProductDelete.as_view(), name='products_delete'),
    path('products/create/', views.ProductCreate.as_view(), name='products_create'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

from django.contrib.auth.models import User
# Create your models here.
PRACTICES = (
    ('M', 'Morning'),
    ('N', 'Noon'),
    ('K', 'Night')
)

class Product(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Instrument(models.Model):  
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField()
    description = models.TextField(max_length=250)
    products = models.ManyToManyField(Product)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.make
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'instrument_id': self.id})

class Practice(models.Model):
    date = models.DateField('practice time')
    practice = models.CharField(
        max_length = 1,
        choices = PRACTICES,
        default = PRACTICES[0][0]
    ) 

    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_practice_display()} on {self.date}"  
    
    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for instrument_id: {self.instrument_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Practice

class PracticeForm(ModelForm):
  class Meta:
    model = Practice
    fields = ['date', 'practice']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
import boto3

from .models import Instrument, Product, Photo
from .forms import PracticeForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'catcollector-fr'

# Create your views here.
@login_required
def add_photo(request, instrument_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
        
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, instrument_id=instrument_id)
            photo.save()
        
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', instrument_id=instrument_id)

@login_required
def assoc_product(request, instrument_id, product_id):
  Instrument.objects.get(id=instrument_id).products.add(product_id)
  return redirect('detail', instrument_id=instrument_id)

@login_required
def dissoc_product(request, instrument_id, product_id):
    Instrument.objects.get(id=instrument_id).products.remove(product_id)
    return redirect('detail', instrument_id=instrument_id)

def home(request):  
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def instruments_index(request):
    instruments = Instrument.objects.filter(user=request.user)
    return render(request, 'instruments/index.html', { 'instruments' : instruments })

@login_required
def instruments_detail(request, instrument_id):
    instrument = Instrument.objects.get(id=instrument_id)
    products_instrument_doesnt_have = Product.objects.exclude(id__in = instrument.products.all().values_list('id'))
    practice_form = PracticeForm()
    return render(request, 'instruments/detail.html', { 'instrument': instrument, 'practice_form' : practice_form, 'products' : products_instrument_doesnt_have })

@login_required
def add_practice(request, instrument_id):
    form = PracticeForm(request.POST)
    if form.is_valid():
        new_practice = form.save(commit=False)
        new_practice.instrument_id = instrument_id
        new_practice.save()
    return redirect('detail', instrument_id=instrument_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid Sign Up. Try Again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class InstrumentCreate(LoginRequiredMixin, CreateView):
    model = Instrument
    fields = ['make', 'model', 'year', 'description']
    success_url = '/instruments/'

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)

class InstrumentUpdate(LoginRequiredMixin, UpdateView):
    model = Instrument
    fields = ['model', 'year', 'description']

class InstrumentDelete(LoginRequiredMixin, DeleteView):
  model = Instrument
  success_url = '/instruments/'

class ProductList(LoginRequiredMixin, ListView):
    model = Product

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product

class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['name']
    success_url = '/products/'

class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name']
    success_url = '/products/'

class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = '/products/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Instrument Collector</h1>
<hr />
<p>Hire the Instrument Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Instrument Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;InstrumentCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'instruments_create' %}">Add an Instrument</a></li>
          <li><a href="{% url 'index' %}">View All Instruments</a></li>
          <li><a href="{% url 'products_create' %}">Add a Product</a></li>
          <li><a href="{% url 'products_index' %}">View All Products</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Instrument Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/instruments/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Instrument Details</h1>
<div class="row">
<div class="col s6">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ instrument.make }}</span>
    <p>Model: {{ instrument.model }}</p>
    <p>Year: {{ instrument.year }}</p>
    <p>Description: {{instrument.description}}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'instruments_update' instrument.id %}">Edit</a>
    <a href="{% url 'instruments_delete' instrument.id %}">Delete</a>
  </div>
</div>
  {% for photo in instrument.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' instrument.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
    </form>

</div>
<div class="col s6">
    <form action="{% url 'add_practice' instrument.id %}" method="post">
        {% csrf_token %}
        {{ practice_form.as_p }}
        <input type="submit" class="btn" value="Add Practice">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Practice</th></tr>
      </thead>
      <tbody>
        {% for practice in instrument.practice_set.all %}
          <tr>
            <td>{{practice.date}}</td>
            <td>{{practice.get_practice_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
<hr>
<div class="row">
 <div class="col s6">
  <h3>{{ instrument.make }}'s Products</h3>
  {% if instrument.products.count %}
   {% for product in instrument.products.all %}
    <div class="card">
     <div class="card-content">
      <span class="card-title">
       A {{ product.name }}
      </span>
      <div class="card-action">
        <form action="{% url 'dissoc_product' instrument.id product.id %}" method="post">
            {% csrf_token %}
          <button type="submit" class="btn red ">Remove</button>
        </form>
      </div>
    </div>
 </div>
 {% endfor %}
 {% else %}
 <h5>No Products</h5>{% endif %}
</div>
<div class="col s6">
    <h3>Available Products</h3>
    {% if products.count %}
      {% for product in products.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ product.name }}</span> 
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_product' instrument.id product.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{instrument.make}} Already Has All Products Available</h5>
    {% endif %}
  </div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_practice');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/instruments/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Instrument List</h1>

{% for instrument in instruments %}
  <div class="card">
    <a href="{% url 'detail' instrument.id %}">
    <div class="card-content">
      <span class="card-title">{{ instrument.make }}</span>
      <p>Model: {{ instrument.model }}</p>
      <p>Year: {{ instrument.year }}</p>
        <p>Description: {{ instrument.description }}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/instrument_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Instrument</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' instrument.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/instrument_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Instrument</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Product</h1>

<h4>Are you sure you want to delete the <span>{{ object.name }}</span>?</h4>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete" class="btn red">
    <a class="btn blue" href="{% url 'products_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/product_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="card">
    <div class="card-content">
        <span class="card-title">A {{ object.name }}
    </div>
    <div class="card-action">
        <a href="{% url 'products_update' object.id %}">Edit</a>
        <a href="{% url 'products_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/product_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span>{{ object.name }}</span></h1>
{% else %}
    <h1>Add Product</h1>
{% endif %}


<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" class="btn blue">
    <a class="btn red" href="{% url 'products_index' %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/product_list.html
{% extends 'base.html' %}

{% block content %}

{% if object_list.count == 0 %}
    <h3 class="red-text">There are no Products</h3>
    <a href="{% url 'products_create' %}">Add a Product</a>
{% else %}
    {% for product in object_list %}
    <div class="card">
        <a href="{% url 'products_detail' product.id %}">
            <div class="card-content">
                <span class="card-title">A {{ product.name }}</span>
            </div>
        </a>
    </div>
    {% endfor %}
{% endif %}

{% endblock %}